services:
  mysql:
    image: mysql:8.3
    container_name: my-spring-mysql
    environment:
      MYSQL_ROOT_HOST: "%"
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DEFAULT_AUTHENTICATION_PLUGIN: mysql_native_password
      TZ: Asia/Seoul
    ports:
      - "3308:3306"
    volumes:
      - mysql-data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql:ro

  qdrant:
    image: qdrant/qdrant:v1.13.4
    container_name: qdrant
    restart: unless-stopped
    ports:
      - "6333:6333"   # HTTP / Web UI (http://localhost:6333/dashboard)
    volumes:
      - qdrant-storage:/qdrant/storage


  cache-server:
    image: redis:7.4
    container_name: my-redis
    restart: unless-stopped
    ports:
      - "6379:6379"

  app:
    container_name: my-spring-app
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - mysql
      - cache-server
      - qdrant
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/${MYSQL_DATABASE}
      SPRING_DATASOURCE_USERNAME: ${MYSQL_USER}
      SPRING_DATASOURCE_PASSWORD: ${MYSQL_PASSWORD}
      SPRING_REDIS_HOST: cache-server
      SPRING_REDIS_PORT: 6379
      QDRANT_URL: http://qdrant:6333

volumes:
  mysql-data:
  qdrant-storage:

