name: "🐛 Bug"
description: "버그 발견"
labels: ["bug"]
body:
  - type: textarea
    attributes:
      label: 📄 설명
      description: 발생한 문제에 대해 구체적으로 작성해 주세요.
      placeholder: 자세히 적을수록 좋습니다!
    validations:
      required: true
  - type: textarea
    attributes:
      label: ✅ 기대한 동작
      description: 정상적으로 동작했을 때 어떻게 되어야 하는지 작성해 주세요.
      placeholder: 예상되는 정상 결과를 적어주세요.
    validations:
      required: true
  - type: textarea
    attributes:
      label: 🙋🏻 참고 자료
      description: 참고 자료가 있다면 작성해 주세요.
